name: Publish GH - Pages

on:
  push:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Build
      run: dotnet publish WhereTheyStand.Wasm -c Release
    - name: Mkdir toPublish
      run: mkdir toPublish
    - name: Move Blazor Output into Place
      run: mv WhereTheyStand.Wasm/bin/Release/net6.0/publish/wwwroot toPublish/
    - name: Update gitattributes
      run: mv toPublish/gitattributes toPublish/.gitattributes

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: toPublish
